name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -rf .git
          git init
          git lfs install
          # ensure .gitattributes is tracked
          git add .
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -m "Sync to Hugging Face"
          git push --force https://DSK005:$HF_TOKEN@huggingface.co/spaces/DSK005/OpenRescue-Sim master:main
